'use client';
import { Toaster } from "react-hot-toast";
import Navbar from "../../components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { UserContext } from "../../lib/context";
import { useEffect, useState } from 'react';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useUserData } from "../../lib/hooks";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const userData = useUserData();

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContext.Provider value={userData}>
          <Navbar />
          {children}
          <Toaster />
        </UserContext.Provider>
      </body>
    </html>
  );
}
